finance_and_technology/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
]

finance_and_technology/finance_and_technology/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    path('accounts/', include('accounts.urls')),
    path('processing/', include('processing.urls')),
]

finance_and_technology/processing/urls.py
from django.urls import path
from . import views

app_name = 'processing'

urlpatterns = [
    path('buscar_fundo/', views.buscaFundo_view, name = 'buscar_fundo'),
    path('escolher_fundo/', views.escolherFundo_view, name = 'escolher_fundo'),
    path('fundo/', views.fundo_view, name = 'fundo'),
    path('xlsx_composicao_carteira/', views.xlsx_composicao_carteira_view, name = 'xlsx_composicao_carteira'),
]

finance_and_technology/accounts/models.py
from django.db import models

# Create your models here.

finance_and_technology/processing/models.py
from django.db import models

# Create your models here.

finance_and_technology/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

finance_and_technology/finance_and_technology/views.py
from django.shortcuts import render, redirect
# from scripts_proprios import funcoes

def home_view(request):
    return render(request, 'home.html')

# def resultado_view(request):
#     if request.method == 'POST':
#         print('foi post')
#         resultado = funcoes.somar(request)
#         print('resultado = ' + str(resultado))
#         return render(request, 'resultado.html', {'resultado': resultado})
#     else:
#         return redirect('home')

finance_and_technology/processing/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from scripts_proprios import autenticacao, acessar_info, organizar_dados, excel_related
from base64 import b64encode
from io import BytesIO
from pprint import pprint

import json


# Create your views here.
@login_required(login_url = '/accounts/login/')
def buscaFundo_view(request):
    [img_data, cookie_val_1, cookie_val_2] = autenticacao.imagem_e_sessao()
    imagem_captcha = b64encode(img_data).decode("utf-8")

    return render(request, 'processing/buscar_fundo.html', {'imagem_captcha' : imagem_captcha, 'cookie_val_1': cookie_val_1, 'cookie_val_2': cookie_val_2})

@login_required(login_url = '/accounts/login/')
def escolherFundo_view(request):
    if request.method == 'POST':
        enviar_dados_resultado =  autenticacao.enviar_dados(request)
        lista_fundos = enviar_dados_resultado[0]
        argumentos_aspnet = enviar_dados_resultado[1]
        cookie_val_1 = request.POST['cookie_val_1']
        cookie_val_2 = request.POST['cookie_val_2']
        return render(request, 'processing/escolher_fundo.html', {'lista_fundos' : lista_fundos, 'cookie_val_1': cookie_val_1, 'cookie_val_2': cookie_val_2, 'argumentos_aspnet': argumentos_aspnet})
    else:
        return redirect('processing:buscar_fundo')

@login_required(login_url = '/accounts/login/')
def fundo_view(request):
    if request.method == 'POST':
        [response, argumentos_aspnet, request_old] = autenticacao.retornar_fundo(request)
        table_header = response[0]
        table_content = response[1:]
        return render(request, 'processing/fundo.html', {'table_header': table_header,
        'table_content': table_content,
        'argumentos_aspnet': argumentos_aspnet,
        'cookie_val_1': request_old.POST.get('cookie_val_1'),
        'cookie_val_2': request_old.POST.get('cookie_val_2')})
    else:
        return redirect('processing:buscar_fundo')

@login_required(login_url = '/accounts/login/')
def xlsx_composicao_carteira_view(request):
    # 1º lugar: pegar composição padrão
    soup_1 = acessar_info.pegar_soup_resposta(request)
    posicionamento = organizar_dados.extrair_posicionamento(soup_1)
    print('Data 1 processada')
    lista_datas = organizar_dados.extrair_datas(soup_1)
    pk_partic = organizar_dados.extrair_pkPartic(soup_1)
    request_2 = autenticacao.atualizar_request(request, soup_1)
    # pprint(lista_datas)

    # 2º lugar: Criar lista de posicionamentos
    historico = [posicionamento]

    # # 3º lugar: append apenas o segundo posicionamento
    # soup_adicional = acessar_info.pegar_soup_resposta(request_2, [lista_datas[1]])[0]
    # posicionamento_adicional = organizar_dados.extrair_posicionamento(soup_adicional)
    # historico.append(posicionamento_adicional)

    # 3º lugar: Append o que tiver a mais
    if len(lista_datas)>1:
        print('Essas são as datas: ')
        pprint(lista_datas)
        soups_adicionais = acessar_info.pegar_soup_resposta(request_2, lista_datas[1:], pk_partic)
        i = 2
        for soup_adicional in soups_adicionais:
            posicionamento_adicional = organizar_dados.extrair_posicionamento(soup_adicional)
            historico.append(posicionamento_adicional)
            print('Data ' + str(i) + ' processada')
            i = i + 1

    # 4º lugar: Colocar histórico no excel e retornar excel
    # ------------ TESTE ------------
    with open('resultado_fundo.txt', 'w') as outfile:
        json.dump(historico, outfile)
    # ----------- TESTOU -----------
    excel = excel_related.colocar_no_excel(historico)
    return excel

finance_and_technology/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block titulo %}
  <title>Log in</title>
{% endblock %}

{% block conteudo %}
  <h1>Log in</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
  </form>

{% endblock %}

finance_and_technology/processing/templates/processing/buscar_fundo.html
{% extends 'base_layout.html' %}

{% block titulo %}
  <title>Finance Hero: Buscar Fundo</title>
{% endblock %}

{% block conteudo %}
  <h1>Coloque as caracteristicas do fundo</h1>
  <form class="caracteristicas" action="{% url 'processing:escolher_fundo' %}" method="post">
    {% csrf_token %}
    <p>Nome ou CNPJ do fundo: <input type="text" name="nome_ou_cnpj"></p>
    <div class="captcha">
      <img src="data:;base64,{{ imagem_captcha }}"/>
    </div>
    <p>Captcha acima: <input type="number" name="captcha"></p>
    <input type="hidden" name="cookie_val_1" value="{{ cookie_val_1 }}">
    <input type="hidden" name="cookie_val_2" value="{{ cookie_val_2 }}">
    <input type="submit", value="Ok">
  </form>
{% endblock %}

finance_and_technology/processing/templates/processing/escolher_fundo.html
{% extends 'base_layout.html' %}

{% block titulo %}
  <title>Finance Hero: Escolher fundo</title>
{% endblock %}

{% block conteudo %}
  <table><caption>Fundos encontrados</caption>
    <thead>
      <tr>
        <th>Nome do fundo</th>
        <th>CNPJ</th>
        <th>Tipo de fundo</th>
        <th>Composicao da Carteira</th>

        {% comment %}
        <th colspan="2">CNPJ</th>
        {% endcomment %}

      </tr>
    </thead>
    <tbody>
      {% for fundo in lista_fundos %}
        <tr>
          <td>{{ fundo.nome }}</td>
          <td>{{ fundo.cnpj }}</td>
          <td style="text-align: center;">{{ fundo.tipo_fundo }}</td>
          <td>
            <form class="escolher_fundo" action="{% url 'processing:xlsx_composicao_carteira' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="link_1" value="{{ fundo.link_1 }}">
              <input type="hidden" name="link_2" value="{{ fundo.link_2 }}">
              <input type="hidden" name="argumentos_aspnet_Form1" value="{{ argumentos_aspnet.Form1 }}">
              <input type="hidden" name="argumentos_aspnet___EVENTARGUMENT" value="{{ argumentos_aspnet.EVENTARGUMENT }}">
              <input type="hidden" name="argumentos_aspnet___VIEWSTATE" value="{{ argumentos_aspnet.VIEWSTATE }}">
              <input type="hidden" name="argumentos_aspnet___VIEWSTATEGENERATOR" value="{{ argumentos_aspnet.VIEWSTATEGENERATOR }}">
              <input type="hidden" name="argumentos_aspnet___EVENTVALIDATION" value="{{ argumentos_aspnet.EVENTVALIDATION }}">

              <input type="hidden" name="cookie_val_1" value="{{ cookie_val_1 }}">
              <input type="hidden" name="cookie_val_2" value="{{ cookie_val_2 }}">
              <input type="submit", value="Ir">
            </form>
          </td>

          {% comment %}
          <td>{{ fundo.tipo_fundo }}</td>
          {% endcomment %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

finance_and_technology/processing/templates/processing/fundo.html
{% extends 'base_layout.html' %}

{% block titulo %}
  <title>Finance Hero: Fundo</title>
{% endblock %}

{% block conteudo %}
  <h1>Informações abaixo</h1>

  <table><caption>Posições do fundo </caption>
    <thead>
      <tr>
        {% for celula in table_header%}
          <th>{{celula}}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
      <form class="escolher_fundo" action="{% url 'processing:xlsx' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="argumentos_aspnet_Form1" value="{{ argumentos_aspnet.Form1 }}">
        <input type="hidden" name="argumentos_aspnet___EVENTARGUMENT" value="{{ argumentos_aspnet.EVENTARGUMENT }}">
        <input type="hidden" name="argumentos_aspnet___VIEWSTATE" value="{{ argumentos_aspnet.VIEWSTATE }}">
        <input type="hidden" name="argumentos_aspnet___VIEWSTATEGENERATOR" value="{{ argumentos_aspnet.VIEWSTATEGENERATOR }}">
        <input type="hidden" name="argumentos_aspnet___EVENTVALIDATION" value="{{ argumentos_aspnet.EVENTVALIDATION }}">
        <input type="hidden" name="cookie_val_1" value="{{ cookie_val_1 }}">
        <input type="hidden" name="cookie_val_2" value="{{ cookie_val_2 }}">
        <input type="submit", value="Baixar csv genérico">
      </form>

      {% for linha in table_content %}
        <tr>
          {% for celula in linha %}
            <td>{{celula}}</td>
          {% endfor %}
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

finance_and_technology/processing/templates/processing/resultado_soma.html
{% extends 'base_layout.html' %}

{% block titulo %}
  <title>Resultado da soma</title>
{% endblock %}

{% block conteudo %}
  <p>Resultado = {{resultado}}</p>
{% endblock %}

finance_and_technology/templates/base_layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% block titulo %}
    {% endblock%}
  </head>
  <body>
    <a href="{% url 'home' %}">Home</a>
    {% if user.is_authenticated %}
      <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Logout</button>
      </form>
    {% else %}
      <a href="{% url 'accounts:login' %}">Login</a>
    {% endif %}
    {% block conteudo %}
    {% endblock%}
  </body>
</html>

finance_and_technology/templates/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Finance Hero: O Herói das Finanças</title>
</head>
<body>
  <div class="majorlink">
    <a href="{% url 'accounts:login' %}">Login</a>
  </div>
  <div class="majorlink">
    <a href="{% url 'processing:buscar_fundo' %}">Consulta à composição de carteiras</a>
  </div>
</body>
</html>